config/routes.rb
Rails.application.routes.draw do
  resources :pokemons
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "pokemons#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  validates :name, presence: true
  validates :type_1, presence: true
  validates :type_2, presence: true
  validates :total , presence: true
  validates :hp , presence: true
  validates :attack , presence: true
  validates :defense , presence: true
  validates :sp_atk , presence: true
  validates :sp_def , presence: true
  validates :speed , presence: true
  validates :generation , presence: true
  validates :legendary , inclusion: {in: [true, false]}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token # this is unsafe but enough for a demo !

end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: %i[ show edit update destroy ]

  # GET /pokemons or /pokemons.json
  def index
    @from ||= params[:from] 
    @from = 0 if @from.to_i < 0
    @per_page ||= params[:per_page] 
    if @from && @per_page
      @pokemons = Pokemon.offset(@from.to_i).limit(@per_page)
    else
      @pokemons = Pokemon.all
    end
  end

  # GET /pokemons/1 or /pokemons/1.json
  def show
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons or /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to pokemon_url(@pokemon), notice: "Pokemon was successfully created." }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1 or /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to pokemon_url(@pokemon), notice: "Pokemon was successfully updated." }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1 or /pokemons/1.json
  def destroy
    @pokemon.destroy

    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: "Pokemon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pokemon_params
      params.require(:pokemon).permit(:name, :type_1, :type_2, :total, :hp, :attack, :defense, :sp_atk, :sp_def, :speed, :generation, :legendary)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemons/_form.html.erb
<%= form_with(model: pokemon) do |form| %>
  <% if pokemon.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
        <% pokemon.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :type_1, style: "display: block" %>
    <%= form.text_field :type_1 %>
  </div>

  <div>
    <%= form.label :type_2, style: "display: block" %>
    <%= form.text_field :type_2 %>
  </div>

  <div>
    <%= form.label :total, style: "display: block" %>
    <%= form.number_field :total %>
  </div>

  <div>
    <%= form.label :hp, style: "display: block" %>
    <%= form.number_field :hp %>
  </div>

  <div>
    <%= form.label :attack, style: "display: block" %>
    <%= form.number_field :attack %>
  </div>

  <div>
    <%= form.label :defense, style: "display: block" %>
    <%= form.number_field :defense %>
  </div>

  <div>
    <%= form.label :sp_atk, style: "display: block" %>
    <%= form.number_field :sp_atk %>
  </div>

  <div>
    <%= form.label :sp_def, style: "display: block" %>
    <%= form.number_field :sp_def %>
  </div>

  <div>
    <%= form.label :speed, style: "display: block" %>
    <%= form.number_field :speed %>
  </div>

  <div>
    <%= form.label :generation, style: "display: block" %>
    <%= form.number_field :generation %>
  </div>

  <div>
    <%= form.label :legendary, style: "display: block" %>
    <%= form.check_box :legendary %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pokemons/_pokemon.html.erb
<div id="<%= dom_id pokemon %>">
  <p>
    <strong>Name:</strong>
    <%= pokemon.name %>
  </p>

  <p>
    <strong>Type 1:</strong>
    <%= pokemon.type_1 %>
  </p>

  <p>
    <strong>Type 2:</strong>
    <%= pokemon.type_2 %>
  </p>

  <p>
    <strong>Total:</strong>
    <%= pokemon.total %>
  </p>

  <p>
    <strong>Hp:</strong>
    <%= pokemon.hp %>
  </p>

  <p>
    <strong>Attack:</strong>
    <%= pokemon.attack %>
  </p>

  <p>
    <strong>Defense:</strong>
    <%= pokemon.defense %>
  </p>

  <p>
    <strong>Sp atk:</strong>
    <%= pokemon.sp_atk %>
  </p>

  <p>
    <strong>Speed:</strong>
    <%= pokemon.speed %>
  </p>

  <p>
    <strong>Generation:</strong>
    <%= pokemon.generation %>
  </p>

  <p>
    <strong>Legendary:</strong>
    <%= pokemon.legendary %>
  </p>

</div>

app/views/pokemons/edit.html.erb
<h1>Editing pokemon</h1>

<%= render "form", pokemon: @pokemon %>

<br>

<div>
  <%= link_to "Show this pokemon", @pokemon %> |
  <%= link_to "Back to pokemons", pokemons_path %>
</div>

app/views/pokemons/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pokemons</h1>
<%if @from && @per_page %>
<div id="nav">
<%= link_to "<- PREVIOUS", pokemons_path(from:  @from.to_i - @per_page.to_i, per_page: @per_page), style: "float:left;" %>
<%= link_to "NEXT ->", pokemons_path(from:  @from.to_i + @per_page.to_i , per_page: @per_page), style: "float:right;" %>
<br/>
</div>
<% end %>
<div id="pokemons" style="text-align: center;">
  <% @pokemons.each do |pokemon| %>
    <%= render pokemon %>
    <p>
      <%= link_to "Show this pokemon", pokemon %>
    </p>
  <% end %>
</div>

<%= link_to "New pokemon", new_pokemon_path %>

app/views/pokemons/new.html.erb
<h1>New pokemon</h1>

<%= render "form", pokemon: @pokemon %>

<br>

<div>
  <%= link_to "Back to pokemons", pokemons_path %>
</div>

app/views/pokemons/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pokemon %>

<div>
  <%= link_to "Edit this pokemon", edit_pokemon_path(@pokemon) %> |
  <%= link_to "Back to pokemons", pokemons_path %>

  <%= button_to "Destroy this pokemon", @pokemon, method: :delete %>
</div>